{
 "title": "Flink",
 "time": { "from": "2023-07-11T06:06:50.939Z", "to": "2023-07-11T07:10:36.049Z" },
 "panels": [
  { "title": "JobManager", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used",
     "legendFormat": "heap memory [{{instance}}]"
    },
    {
     "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used",
     "legendFormat": "non-heap memory [{{instance}}]"
    }
   ]
  },
  {
   "title": "TaskManager",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory used",
     "type": "graph",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used",
       "legendFormat": "heap memory [{{instance}}]"
      },
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used",
       "legendFormat": "non-heap memory [{{instance}}]"
      }
     ]
    },
    {
     "title": "GC Overhead",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time[5m])/1000 + rate(flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time[5m])/1000",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "PrometheusFlink", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_operator_my_g{}/1000000",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_latency_source_id_operator_id_operator_subtask_index_latency{job_id=\"799dcd4bb4cbf47696130043eca4ef92\",quantile=\"0.5\"}",
     "legendFormat": "{{job_name}}"
    }
   ]
  },
  {
   "title": "Num Record In",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsIn",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Num Record Out",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "flink_taskmanager_job_task_numRecordsOut",
     "legendFormat": "{{task_name}}"
    }
   ]
  }
 ]
}